services:
  controller:
    container_name: controller
    image: strato_controller
    network_mode: "host"
    build:
      context: ../../
      dockerfile: ./controller/Dockerfile
    stdin_open: true
    volumes:
      - ./controller-config.toml:/var/strato/server/config.toml
    command: /bin/bash -c "/var/strato/server/target/release/controller"
