protocol = "tcp"

# Three nodes in the topology
[[nodes]]
[topology]
n_nodes = 3

# if you wish to test ping and iperf, you can uncomment the following lines
# [[nodes]]
# node_id = 2
# operating_mode = "max"

# [[nodes]]
# node_id = 4
# operating_mode = "max"

[[routes]]
# node 1 represents the external client
# node 5 represents the internal server
route = [1, 2, 3, 4, 5]


# if you wish to test ping and iperf, you can uncomment the following lines
# [[routes]]
# route = [2, 3, 4]

# [[routes]]
# route = [4, 3, 2]
