protocol = "tcp"

[topology]
n_nodes = 3

# [[nodes]]
# node_id = 1
# operating_mode = "max"

[[routes]]
# node 0 represents the external client
# node 4 represents the internal server
route = [0, 1, 2, 3, 4]
