FROM ubuntu:24.04

# Install curl
RUN apt-get update && apt-get install -y curl

# Copy the client script
COPY client.sh /client.sh

# Make the script executable
RUN chmod +x /client.sh

# Sleep for several seconds before running the script to ensure services are ready
CMD ["/bin/bash", "-c", "sleep 60 && /client.sh"]