# FROM runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel
FROM horovod/horovod/
# Install basic tools
RUN apt-get update && \
    apt-get install -y \
	build-essential\
	net-tools \
	netcat \
	iperf3 &&\
    apt-get clean

# Install python dependencies
RUN pip install transformers \
	datasets \
	pytorch_lightning \
	lightning_horovod

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN echo "source $HOME/.cargo/env" >> $HOME/.bashrc
RUN /root/.cargo/bin/cargo install tokio-console
RUN /bin/bash -c "source /root/.bashrc"
