FROM python:3-alpine

WORKDIR /app

COPY src/server.sh /usr/local/bin/server.sh
RUN chmod +x /usr/local/bin/server.sh \
  && mkdir -p /var/nextmini \
  && ln -s /usr/local/bin/server.sh /var/nextmini/src

CMD ["/usr/local/bin/server.sh"]
