
[package]
name = "swarm-curl"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-splice = "0.2.0"
tracing = "0.1"
tracing-subscriber = "0.3" 
