protocol = "tcp"

# scheduler_type can be "fifo" or "wrr"
scheduler_type = "fifo"

# create a full mesh topology with 4 nodes
[topology]
type = "full_mesh"
n_nodes = 4

[[link_rates]]
src_node_id = 1
dst_node_id = 2
rate = 100_000_000
bucket_size = 9000

# Now the routes for node1 and node2 are [1, 3, 4, 2] and [1, 2]
[[routes]]
route = [ 1, 3, 4, 2 ]

[[flows]]
src_node_id = 1
dst_node_id = 2
flow_spec = { flow_len = { Bytes = 10_000_000_000 }, flow_weight = 1, flow_rate = 1_000_000 }
