protocol = "tcp"

# scheduler_type can be "fifo" or "wrr"
scheduler_type = "fifo"

flow_transport = "lossless_unicast"

# creates a full mesh topology with 4 nodes
[topology]
type = "full_mesh"
full_mesh_config = { n_nodes = 4 }

# [[link_rates]]
# src_node_id = 1
# dst_node_id = 2
# rate = 100_000_000
# bucket_size = 312_000_000

# [[link_rates]]
# src_node_id = 2
# dst_node_id = 1
# rate = 100_000_000
# bucket_size = 312_000_000

# the route from node 1 and node 2 is [1, 3, 4, 2]
[[routes]]
route = [1, 2]

[[routes]]
route = [2, 1]

# # the route for node 3 and node 4
# [[routes]]
# route = [3, 4]

# [[routes]]
# route = [4, 3]

[[flows]]
src_node_id = 1
dst_node_id = 2
flow_spec = { flow_len = { Bytes = 10_000_000_000 }, flow_weight = 1 }
# [[flows]]
# src_node_id = 1
# dst_node_id = 2
# flow_spec = { flow_len = { Bytes = 20_000_000 }, flow_rate = 10_000_000, flow_weight = 1 }
# [[flows]]
# src_node_id = 1
# dst_node_id = 2
# flow_spec = { flow_len = { Bytes = 10_000_000 }, flow_rate = 10_000_000, flow_weight = 1 } 
