version: "3"
services:
  node:
    container_name: nextmini
    hostname: nextmini
    image: nextmini_datapath
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    volumes:
      - .:/var/nextmini
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "/var/node/target/release/nextmini ws://192.168.196.158:3000"
