version: '3'
services:
  controller:
    container_name: controller
    hostname: controller
    image: strato_controller
    build:
        context: ../../
        dockerfile: ./examples/routing/Dockerfile
    stdin_open: true
    volumes:
      - ./config_underlay.json:/var/strato/server/config_underlay.json
      - ./config_overlay.json:/var/strato/server/config_overlay.json
      - ./init.sql:/var/strato/server/init.sql
      - ../../../tools/MLRouting:/var/strato/server/MLRouting
    ports:
      - 10003:10003
      - 10004:10004
    command: /bin/bash -c "node server.js config_underlay.json &
                          sleep 7 &&
                          node server.js config_overlay.json"