CREATE DATABASE strato0;
CREATE DATABASE strato1;
CREATE USER pgusr WITH ENCRYPTED PASSWORD 'pgpwrd';
GRANT ALL PRIVILEGES ON DATABASE strato0 TO pgusr;
GRANT ALL PRIVILEGES ON DATABASE strato1 TO pgusr;
ALTER DATABASE strato0 OWNER TO pgusr;
ALTER DATABASE strato1 OWNER TO pgusr;
