[package]
name = "ringallreduce"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ringallreduce"
path = "src/main.rs"

[dependencies]
anyhow = "1"
bincode = { version = "2.0.1", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

