services:
  mininet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mininet-container
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: "bridge"
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /lib/modules:/lib/modules:ro
      - ./examples:/opt/mininet-examples:ro
    ports:
      - "6633:6633"
      - "6653:6653"
      - "6640:6640"
