services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: ebpf-client
    depends_on:
      - proxy
    networks:
      - ebpf-network
    volumes:
      - /sys:/sys:rw
      - /proc:/proc:rw
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    cap_add:
      - ALL
    privileged: true
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: ebpf-proxy
    depends_on:
      - server
    networks:
      - ebpf-network
    volumes:
      - /sys:/sys:rw
      - /proc:/proc:rw
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    cap_add:
      - ALL
    privileged: true
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ebpf-server
    networks:
      - ebpf-network
    volumes:
      - /sys:/sys:rw
      - /proc:/proc:rw
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
    cap_add:
      - ALL
    privileged: true
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined

networks:
  ebpf-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16