controller_addr = "ws://controller:3000"
private_network_interface = "eth0"
private_network_name = "multicast_demo"
node_id = 2
n_nodes = 1
num_tun_queues = 1
num_packet_processors = 4
channel_capacity = 40000
queue_capacity = 40000
feature = "concurrent"
python_fragmentation_enabled = true
python_fragmentation_max_message_bytes = 655360
python_fragmentation_reassembly_window_bytes = 83886080
python_fragmentation_fragment_timeout_ms = 100000
python_fragmentation_trace_flow_events = true
