controller_addr = "ws://controller:3000"
private_network_interface = "eth0"
private_network_name = "multicast_demo"
node_id = 2
n_nodes = 1
num_tun_queues = 1
num_packet_processors = 4
channel_capacity = 3000
queue_capacity = 4000
feature = "concurrent"
channel_backpressure = true

[reliable]
default_chunk_size = 4096
control_weight = 8
ack_policy = "all"
fec_p = 0
ready_grace_ms = 1500
