protocol = "tcp"

[topology]
type = "full_mesh"
n_nodes = 2

[[flow_weights]]
src_ip = [10,0,0,2]
dst_ip = [10,0,0,1]
src_port = 53744
dst_port = 5201
weight = 1

[[flow_weights]]
src_ip = [10,0,0,2]
dst_ip = [10,0,0,1]
src_port = 57016
dst_port = 5202
weight = 2

