protocol = "tcp"

[[routes]]
route = [[1, 2], [2, 4], [1, 3], [3, 4]]

[[routes]]
route = [[1, 4]]

[[routes]]
route = [[4, 1]]

# [topology]
# type = "fat_tree"
# n_nodes = 4
# fat_tree_config = { k = 2 }

# edges = [[4, 1]]
