protocol = "tcp"
user_space_base_addr = "10.10.0.0"
multicast_pool_base = "239.10.0.0"

[db]
host = "127.0.0.1"
port = "5432"
user = "pgusr"
password = "pgpwrd"
database = "nextmini"

[topology]
type = "full_mesh"
full_mesh_config = { n_nodes = 2 }

[routing]
protocol = "shortest_path"
