protocol = "tcp"

[topology]
type = "ring"
ring_config = { n_nodes = 400 }

[db]
user = "pgusr"
password = "pgpwrd"
host = "postgres"
database = "nextmini"
port = "5432"

# if you wish to test max mode, you can uncomment the following lines
# [[nodes]]
# node_id = 1
# operating_mode = "max"

# if you wish to test the smoltcp as well, you can uncomment the following lines
# [[flows]]
# src_node_id = 1
# dst_node_id = 3
# flow_spec = { flow_len = { Bytes = 10_000_000_000 }, flow_weight = 1 }
