protocol = "tcp"
user_space_base_addr = "192.168.0.0"

[db]
host = "postgres"
port = "5432"
user = "pgusr"
password = "pgpwrd"
database = "nextmini"

[topology]
type = "full_mesh"
full_mesh_config = { n_nodes = 2 }

[routing]
protocol = "shortest_path"
