controller_addr = "ws://controller:3000"
private_network_interface = "eth0"
private_network_name = "python_api"
node_id = 3
num_tun_queues = 1
num_packet_processors = 4
channel_capacity = 4000
queue_capacity = 3000
