# Configuration for Node 1, running on the same VM as the controller.
# VM1 Public IP: 209.38.72.97


# This node's ID, must match one in controller-config.toml
node_id = 1

# --- Public Network ---
# The network interface that has the public IP. From your ifconfig, this is eth0.
public_network_interface = "eth0"
# The port this node will use to listen for connections from other nodes.
# public_network_port = "8080/8081" 
# Explicitly set the public IP address. While the program can detect it,
# setting it here avoids any ambiguity.
public_network_addr = "209.38.72.97"


# --- Private Network ---
# Set a unique name to ensure communication with Node 2 happens over the public network.
private_network_name = "vm1-private"
# The private interface inside the Docker container for the 'network' bridge.
# private_network_addr = "172.16.8.4"
# private_network_port = "8081"
num_tun_queues = 1
num_packet_processors = 1
channel_capacity = 4000
queue_capacity = 3000
feature = "concurrent"