# This is the config for main.py.

[database]
host = "localhost"
port = 5432
user = "pgusr"
password = "pgpwrd"
database = "nextmini"

[solver]
# LP solver type: "mFlow" or "multi_commodity"
type = "mFlow"
