services:
  node:
    container_name: node
    image: strato_datapath
    build:
      context: ../../
      dockerfile: ./dataplane/Dockerfile
    network_mode: "host"
    stdin_open: true
    privileged: true
    volumes:
      - ./config.toml:/var/node/config.toml
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "sleep 5 && ./target/release/strato ${CONTROLLER_ADDR}"
