version: '3.8'

networks:
  nextmini-net:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.8.0/24

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    command: postgres -c max_connections=700 -c shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_USER: pgusr
      POSTGRES_PASSWORD: pgpwrd
      POSTGRES_DB: nextmini
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pgusr", "-d", "nextmini"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - nextmini-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../controller/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  controller:
    image: nextmini_controller
    hostname: controller
    build:
      context: ../../
      dockerfile: ./controller/Dockerfile
    networks:
      - nextmini-net
    ports:
      - 3000:3000
    volumes:
      - ./controller-config.toml:/var/nextmini/config.toml
    depends_on:
      - postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    command: /bin/bash -c "sleep 5 && /var/nextmini/controller"

  dataplane:
    image: nextmini_datapath
    hostname: "node{{.Task.Slot}}"
    build:
      context: ../../
      dockerfile: ./dataplane/Dockerfile
    networks:
      - nextmini-net
    privileged: true
    volumes:
      - ./config.toml:/var/nextmini/config.toml.template
      - ../../tools/:/var/nextmini/tools
      - /dev/net/tun:/dev/net/tun
    depends_on:
      - controller
    cap_add:
      - NET_ADMIN
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    command: |
      /bin/bash -c "
        echo \"Current hostname: $$(hostname)\"
        NODE_ID=$$(hostname | sed 's/node//')
        echo \"Extracted NODE_ID: $$NODE_ID\"
        cp /var/nextmini/config.toml.template /var/nextmini/config.toml
        echo \"\" >> /var/nextmini/config.toml
        echo \"node_id = $$NODE_ID\" >> /var/nextmini/config.toml
        echo \"Generated config file:\"
        cat /var/nextmini/config.toml
        sleep 7 && /var/nextmini/nextmini ws://controller:3000
      "