services:
  strato:
    container_name: strato
    image: strato_datapath_horovod
    build:
      context: ../../
      dockerfile: ./examples/dataplane_horovod_cpu/Dockerfile
    stdin_open: true
    privileged: true
    network_mode: "host"
    volumes:
      - ./ssh:/mnt/shared/ssh
      - ./run_horovod.sh:/horovod/examples/run_horovod.sh
      - ./config.toml:/horovod/examples/config.toml
      - ./measurement:/horovod/examples/measurement
      - ./benchmark.py:/horovod/examples/benchmark.py
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "cp -r /mnt/shared/ssh /root/.ssh &&
      chmod 400 /root/.ssh/id_rsa &&
      chmod +x /horovod/examples/run_horovod.sh &&
      /usr/sbin/sshd -p 12345 &
      /var/node/target/release/strato ws://${CONTROLLER_ADDR}:${CONTROLLER_PORT} --private-network-addr ${LOCAL_STRATO_ADDR} --private-network-port ${LOCAL_STRATO_PORT} --public-network-addr ${LOCAL_STRATO_ADDR} --public-network-port ${LOCAL_STRATO_PORT} --node-id ${STRATO_NODE_ID} "
