protocol = "tcp"

[[nodes]]
node_id = 1
operating_mode = "max"

# [[nodes]]
# node_id = 3
# operating_mode = "max"

[topology]
# type = "full_mesh"
n_nodes = 19

[[routes]]
route = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

[[routes]]
route = [19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]
