# docker-compose.yml
version: '3'

services:
  strato:
    container_name: strato
    hostname: strato
    image: strato_datapath_horovod
    build:
        context: ../../
        dockerfile: ./examples/strato_on_strato/Dockerfile
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/mnt/shared/ssh
      - ./run_horovod.sh:/horovod/examples/run_horovod.sh
      - ./config_underlay.toml:/horovod/examples/config_underlay.toml
      - ./config_overlay.toml:/horovod/examples/config_overlay.toml
    ports:
      - 10001:10001
      - 10002:10002
    cap_add:
        - NET_ADMIN
    command: /bin/bash -c "cp -r /mnt/shared/ssh/ /root/.ssh && 
                          chmod 400 /root/.ssh/id_rsa &&
                          chmod +x /horovod/examples/run_horovod.sh &&
                          /usr/sbin/sshd -p 12345 & 
                          sleep 7 && 
                          /var/node/target/release/strato ws://${CONTROLLER_ADDR}:10003 --config-path config_underlay.toml &
                           sleep 20 &&
                          /var/node/target/release/strato ws://${CONTROLLER_ADDR}:10004 --config-path config_overlay.toml"
                  


    
        
