protocol = "tcp"

[topology]
type = "full_mesh"
n_nodes = 3

[[flows]]
src_node_id = 1
dst_node_id = 2
flow_size = { Bytes = 1_000_000_000_0 }

[[flows]]
src_node_id = 1
dst_node_id = 3
flow_size = { Bytes = 1_000_000_000_0 }

[[flows]]
src_node_id = 3
dst_node_id = 2
flow_size = { Bytes = 1_000_000_000_0 }
