protocol = "tcp"

[topology]
type = "full_mesh"
n_nodes = 3

[[flows]]
src_node_id = 1
dst_node_id = 2
flow_spec = { flow_len = { Bytes = 10_000_000_000 }, flow_rate = 1_000_000 }

# [[flows]]
# src_node_id = 1
# dst_node_id = 3
# flow_spec = { flow_len = { Bytes = 10_000_000_000 }, flow_weight = 1 }

# [[flows]]
# src_node_id = 3
# dst_node_id = 2
# flow_spec = { flow_len = { Bytes = 10_000_000_000 }, flow_weight = 1 }
