protocol = "tcp"
scheduler_type = "wrr"

[topology]
n_nodes = 3

[[link_rates]]
src_node_id = 1
dst_node_id = 2
rate = 100_496_714
bucket_size = 9000

[[link_rates]]
src_node_id = 2
dst_node_id = 3
rate = 99_861_735
bucket_size = 9000

[[link_rates]]
src_node_id = 3
dst_node_id = 1
rate = 100_647_688
bucket_size = 9000

[[link_rates]]
src_node_id = 2
dst_node_id = 1
rate = 101_523_029
bucket_size = 9000

[[link_rates]]
src_node_id = 3
dst_node_id = 2
rate = 99_765_846
bucket_size = 9000

[[link_rates]]
src_node_id = 1
dst_node_id = 3
rate = 99_765_863
bucket_size = 9000

[[routes]]
route = [1, 2]

[[routes]]
route = [2, 1]

[[routes]]
route = [2, 3]

[[routes]]
route = [3, 2]

[[routes]]
route = [3, 1]

[[routes]]
route = [1, 3]
