services:
  controller:
    container_name: controller
    hostname: controller
    image: strato_controller
    build:
      context: ../../
      dockerfile: ./controller/Dockerfile
    networks:
      network:
        ipv4_address: 172.16.8.2
    stdin_open: true
    volumes:
      - ./controller-config.toml:/var/strato/server/config.toml
    ports:
      - 5432:5432
      - 3000:3000
    command: /bin/bash -c "/var/strato/server/target/release/controller"
