#!/usr/bin/env python3
from __future__ import annotations

import argparse
import pathlib


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate namespace-mode configs for a ring topology plus many identical flows."
        )
    )
    parser.add_argument("--n-nodes", type=int, default=136, help="Total node count.")
    parser.add_argument("--n-flows", type=int, default=180, help="Number of flows to generate.")
    parser.add_argument("--src", type=int, default=1, help="Flow source node id.")
    parser.add_argument("--dst", type=int, default=136, help="Flow destination node id.")
    parser.add_argument(
        "--flow-bytes",
        type=int,
        default=1_000_000,
        help="Per-flow byte budget (FlowLen::Bytes).",
    )
    parser.add_argument(
        "--flow-rate",
        type=int,
        default=500_000,
        help="Per-flow rate in bytes/sec (used for pacing).",
    )
    parser.add_argument("--flow-weight", type=int, default=1, help="Per-flow scheduler weight.")
    parser.add_argument(
        "--controller-addr",
        type=str,
        default="127.0.0.1:3000",
        help="Controller address for dataplane config.",
    )
    parser.add_argument(
        "--db-host",
        type=str,
        default="170.16.8.2",
        help="Postgres host as seen by the controller container.",
    )
    parser.add_argument(
        "--out-dir",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent,
        help="Directory to write config files into.",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.n_nodes <= 1:
        raise SystemExit("--n-nodes must be > 1 for namespace mode.")
    if args.n_flows <= 0:
        raise SystemExit("--n-flows must be > 0.")
    if args.flow_bytes < 0:
        raise SystemExit("--flow-bytes must be >= 0.")
    if args.flow_rate <= 0:
        raise SystemExit("--flow-rate must be > 0 (required for pacing).")
    if args.flow_weight <= 0:
        raise SystemExit("--flow-weight must be > 0.")
    if not (1 <= args.src <= args.n_nodes):
        raise SystemExit("--src must be within [1, --n-nodes].")
    if not (1 <= args.dst <= args.n_nodes):
        raise SystemExit("--dst must be within [1, --n-nodes].")
    if args.src == args.dst:
        raise SystemExit("--src and --dst must differ.")


def render_controller_config(args: argparse.Namespace) -> str:
    forward = [args.src, args.dst]
    reverse = [args.dst, args.src]

    header = f"""# Generated by examples/ns-flow/generate.py
# n_nodes={args.n_nodes} n_flows={args.n_flows} src={args.src} dst={args.dst}
protocol = "tcp"
flow_transport = "lossless_unicast"

[topology]
type = "ring"
ring_config = {{ n_nodes = {args.n_nodes} }}

[db]
user = "pgusr"
password = "pgpwrd"
host = "{args.db_host}"
database = "nextmini"
port = "5432"

[[routes]]
route = {forward}

[[routes]]
route = {reverse}
"""

    flow_line = (
        f'flow_spec = {{ flow_len = {{ Bytes = {args.flow_bytes} }}, '
        f"flow_rate = {args.flow_rate}, flow_weight = {args.flow_weight}, "
        f'transport = "lossless_unicast" }}'
    )

    flows = []
    for _ in range(args.n_flows):
        flows.append("[[flows]]")
        flows.append(f"src_node_id = {args.src}")
        flows.append(f"dst_node_id = {args.dst}")
        flows.append(flow_line)
        flows.append("")

    return header + "\n" + "\n".join(flows).rstrip() + "\n"


def render_dataplane_config(args: argparse.Namespace) -> str:
    return f"""# Generated by examples/ns-flow/generate.py
private_network_interface = "eth0"
private_network_name = "net1"
n_nodes = {args.n_nodes}
num_tun_queues = 1
num_packet_processors = 8
channel_capacity = 4000
channel_backpressure = true
queue_capacity = 3000
feature = "concurrent"
# Disable per-node TUN interface for the namespace flows example.
enable_local_interface = false
controller_addr = "{args.controller_addr}"

# Faster startup/memory-footprint experiments:
# stretches metrics reporting interval to reduce timer wakeups
metrics_collection_interval = 3600
# Namespace-mode tuning (all values in ms).
controller_connect_timeout_ms = 30000
interval_between_spawn = 1
child_start_delay_ms = 0
"""


def main() -> None:
    args = parse_args()
    validate_args(args)

    out_dir: pathlib.Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    controller_cfg_path = out_dir / "controller-config.toml"
    dataplane_cfg_path = out_dir / "config.toml"

    controller_cfg_path.write_text(render_controller_config(args), encoding="utf-8")
    dataplane_cfg_path.write_text(render_dataplane_config(args), encoding="utf-8")

    print(f"Wrote {controller_cfg_path}")
    print(f"Wrote {dataplane_cfg_path}")


if __name__ == "__main__":
    main()
