#!/usr/bin/env python3
from __future__ import annotations

import argparse
import pathlib


TOPOLOGY_EDGES = [
    (1, 2),
    (1, 3),
    (2, 4),
    (2, 5),
    (3, 4),
    (3, 5),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate config and payload files for the namespace lossless integration harness."
    )
    parser.add_argument("--case-name", required=True)
    parser.add_argument("--mode", choices=("plain", "fec"), required=True)
    parser.add_argument("--receivers", type=int, choices=(1, 2), required=True)
    parser.add_argument("--trees", type=int, choices=(1, 2), required=True)
    parser.add_argument("--block-size", type=int, required=True)
    parser.add_argument("--symbols-per-block", type=int, required=True)
    parser.add_argument("--payload-size", type=int, required=True)
    parser.add_argument(
        "--controller-addr",
        default="ws://127.0.0.1:3000",
        help="Host-local controller address for dataplane startup.",
    )
    parser.add_argument(
        "--db-host",
        default="127.0.0.1",
        help="Postgres host as seen by the host-local controller.",
    )
    parser.add_argument("--out-dir", type=pathlib.Path, required=True)
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.block_size <= 0:
        raise SystemExit("--block-size must be positive.")
    if args.symbols_per_block <= 0:
        raise SystemExit("--symbols-per-block must be positive.")
    if args.payload_size <= 0:
        raise SystemExit("--payload-size must be positive.")
    if args.mode == "plain" and args.trees != 1:
        raise SystemExit("plain mode currently supports exactly one tree in this harness.")


def receiver_ids(count: int) -> list[int]:
    return [4] if count == 1 else [4, 5]


def tree_edges(tree_count: int, receiver_count: int) -> list[tuple[int, list[tuple[int, int]]]]:
    receivers = receiver_ids(receiver_count)
    trees: list[tuple[int, list[tuple[int, int]]]] = []

    first = [(1, 2)] + [(2, rid) for rid in receivers]
    trees.append((0, first))

    if tree_count > 1:
        second = [(1, 3)] + [(3, rid) for rid in receivers]
        trees.append((1, second))

    return trees


def render_controller_config(args: argparse.Namespace) -> str:
    edges = ",\n    ".join(f"[{src}, {dst}]" for src, dst in TOPOLOGY_EDGES)
    return f"""# Generated by examples/ns-flow/generate_integration.py
protocol = "tcp"

[routing]
protocol = "shortest_path"

[topology]
n_nodes = 5
edges = [
    {edges}
]

[db]
user = "pgusr"
password = "pgpwrd"
host = "{args.db_host}"
database = "nextmini"
port = "5432"
"""


def render_tree_blocks(args: argparse.Namespace) -> str:
    blocks: list[str] = []
    for tree_id, edges in tree_edges(args.trees, args.receivers):
        edge_lines = ", ".join(f"[{src}, {dst}]" for src, dst in edges)
        blocks.append(
            "\n".join(
                [
                    "[[integration_test.trees]]",
                    f"tree_id = {tree_id}",
                    f"edges = [{edge_lines}]",
                ]
            )
        )
    return "\n\n".join(blocks)


def render_dataplane_config(args: argparse.Namespace, payload_path: pathlib.Path, artifact_dir: pathlib.Path) -> str:
    receivers = ", ".join(str(node_id) for node_id in receiver_ids(args.receivers))
    tree_ids = ", ".join(str(tree_id) for tree_id, _ in tree_edges(args.trees, args.receivers))
    fec_enabled = "true" if args.mode == "fec" else "false"

    return f"""# Generated by examples/ns-flow/generate_integration.py
private_network_interface = "eth0"
private_network_name = "net1"
n_nodes = 5
num_tun_queues = 1
num_packet_processors = 1
channel_capacity = 2048
channel_backpressure = true
queue_capacity = 2048
feature = "sequential"
enable_local_interface = false
controller_addr = "{args.controller_addr}"
metrics_collection_interval = 3600
controller_connect_timeout_ms = 30000
interval_between_spawn = 1
child_start_delay_ms = 0

[lossless_runtime_config]
default_block_size = {args.block_size}
ready_grace_ms = 3000
fec_enabled = {fec_enabled}
fec_default_symbols_per_block = {args.symbols_per_block}
fec_default_tree_ids = [{tree_ids}]

[integration_test]
enabled = true
case_name = "{args.case_name}"
group_label = "ns-it-{args.case_name}"
source_node_id = 1
receiver_ids = [{receivers}]
artifact_dir = "{artifact_dir}"
payload_path = "{payload_path}"
group_timeout_ms = 30000
receive_timeout_ms = 60000
poll_interval_ms = 200
src_port = 45000
dst_port = 46000
block_size = {args.block_size}

{render_tree_blocks(args)}
"""


def write_payload(path: pathlib.Path, size: int) -> None:
    payload = bytes((index * 31 + 7) % 256 for index in range(size))
    path.write_bytes(payload)


def main() -> None:
    args = parse_args()
    validate_args(args)

    out_dir = args.out_dir.resolve()
    artifact_dir = out_dir / "artifacts"
    payload_path = out_dir / "payload.bin"
    out_dir.mkdir(parents=True, exist_ok=True)
    artifact_dir.mkdir(parents=True, exist_ok=True)

    write_payload(payload_path, args.payload_size)
    (out_dir / "controller-config.toml").write_text(
        render_controller_config(args), encoding="utf-8"
    )
    (out_dir / "dataplane-config.toml").write_text(
        render_dataplane_config(args, payload_path, artifact_dir), encoding="utf-8"
    )

    print(f"Wrote {out_dir / 'controller-config.toml'}")
    print(f"Wrote {out_dir / 'dataplane-config.toml'}")
    print(f"Wrote {payload_path}")


if __name__ == "__main__":
    main()
