networks:
  nextmini-net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.8.0/24

services:
  node1:
    image: nextmini_datapath
    hostname: "node{{.Task.Slot}}"
    networks:
      - nextmini-net
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/var/nextmini/.ssh
      - ./config.toml:/var/nextmini/config.toml
      - ./lenet5.py:/var/nextmini/lenet5.py
      - ./test.py:/var/nextmini/test.py
      - ./train.sh:/var/nextmini/train.sh
      - ./pyproject.toml:/var/nextmini/pyproject.toml
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "cp -r /var/nextmini/.ssh /root &&
      chmod 400 /root/.ssh/id_rsa && mkdir -p /run/sshd &&
      /usr/sbin/sshd -p 22 &
      sleep 8 &&
      /var/nextmini/nextmini ws://controller:3000 &
      echo \"Node 1 is now running.\" &&
      sleep 15 &&
      ssh-keyscan -H 10.0.0.2 >> /root/.ssh/known_hosts &&
      ssh-keyscan -H 10.0.0.3 >> /root/.ssh/known_hosts &&
      ssh-keyscan -H 10.0.0.4 >> /root/.ssh/known_hosts &&
      sleep infinity"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s

  dataplane:
    image: nextmini_datapath
    hostname: "node{{.Task.Slot}}"
    networks:
      - nextmini-net
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/var/nextmini/.ssh
      - ./config.toml:/var/nextmini/config.toml
      - ./lenet5.py:/var/nextmini/lenet5.py
      - ./test.py:/var/nextmini/test.py
      - ./pyproject.toml:/var/nextmini/pyproject.toml
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "cp -r /var/nextmini/.ssh /root &&
      chmod 400 /root/.ssh/id_rsa && mkdir -p /run/sshd &&
      /usr/sbin/sshd -p 22 &
      sleep 11 &&
      echo \"Node is now running.\" &&
      /var/nextmini/nextmini ws://controller:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
