# docker-compose configuration for the PyTorch distributed example.
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.8.0/24
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    hostname: postgres
    environment:
      POSTGRES_USER: pgusr
      POSTGRES_PASSWORD: pgpwrd
      POSTGRES_DB: nextmini
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pgusr", "-d", "nextmini"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      network:
        ipv4_address: 172.16.8.2
    volumes:
      - ../../controller/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  controller:
    container_name: controller
    hostname: controller
    image: nextmini_controller
    build:
      context: ../../
      dockerfile: ./controller/Dockerfile
    networks:
      network:
        ipv4_address: 172.16.8.3
    stdin_open: true
    volumes:
      - ./controller-config.toml:/var/nextmini/config.toml
    depends_on:
      - postgres
    ports:
      - 3000:3000
    command: /bin/bash -c "sleep 4 && /var/nextmini/controller"

  node1:
    container_name: node1
    hostname: node1
    image: nextmini_datapath_pytorch
    build:
      context: ../../
      dockerfile: ./examples/pytorch/Dockerfile
    networks:
      network:
        ipv4_address: 172.16.8.4
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/mnt/share/.ssh
      - ./config.toml:/var/nextmini/config.toml
      - ./lenet5.py:/var/nextmini/lenet5.py
      - ./test.py:/var/nextmini/test.py
      - ./run_test.sh:/var/nextmini/run_test.sh
      - ./train.sh:/var/nextmini/train.sh
      - ./pyproject.toml:/var/nextmini/pyproject.toml
    depends_on:
      - controller
      - node4
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "mkdir -p /root/.ssh && cp -r /mnt/share/.ssh /root &&
      chmod 400 /root/.ssh/id_rsa &&
      sleep 8 &&
      /var/nextmini/nextmini ws://controller:3000 &&
      sleep 8 &&
      ssh-keyscan -H 10.0.0.2 >> /root/.ssh/known_hosts &&
      ssh-keyscan -H 10.0.0.3 >> /root/.ssh/known_hosts &&
      ssh-keyscan -H 10.0.0.4 >> /root/.ssh/known_hosts
      "

  node2:
    container_name: node2
    hostname: node2
    image: nextmini_datapath_pytorch
    build:
      context: ../../
      dockerfile: ./examples/pytorch/Dockerfile
    networks:
      network:
        ipv4_address: 172.16.8.5
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/mnt/share/.ssh
      - ./config.toml:/var/nextmini/config.toml
      - ./lenet5.py:/var/nextmini/lenet5.py
      - ./test.py:/var/nextmini/test.py
      - ./run_test.sh:/var/nextmini/run_test.sh
      - ./train.sh:/var/nextmini/train.sh
      - ./pyproject.toml:/var/nextmini/pyproject.toml
    depends_on:
      - controller
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "mkdir -p /root/.ssh && cp -r /mnt/share/.ssh /root &&
      chmod 400 /root/.ssh/id_rsa &&
      sleep 11 &&
      /var/nextmini/nextmini ws://controller:3000"

  node3:
    container_name: node3
    hostname: node3
    image: nextmini_datapath_pytorch
    build:
      context: ../../
      dockerfile: ./examples/pytorch/Dockerfile
    networks:
      network:
        ipv4_address: 172.16.8.6
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/mnt/share/.ssh
      - ./config.toml:/var/nextmini/config.toml
      - ./lenet5.py:/var/nextmini/lenet5.py
      - ./test.py:/var/nextmini/test.py
      - ./run_test.sh:/var/nextmini/run_test.sh
      - ./train.sh:/var/nextmini/train.sh
      - ./pyproject.toml:/var/nextmini/pyproject.toml
    depends_on:
      - controller
      - node2
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "mkdir -p /root/.ssh && cp -r /mnt/share/.ssh /root &&
      chmod 400 /root/.ssh/id_rsa &&
      sleep 11 &&
      /var/nextmini/nextmini ws://controller:3000"

  node4:
    container_name: node4
    hostname: node4
    image: nextmini_datapath_pytorch
    build:
      context: ../../
      dockerfile: ./examples/pytorch/Dockerfile
    networks:
      network:
        ipv4_address: 172.16.8.7
    stdin_open: true
    privileged: true
    volumes:
      - ./ssh:/mnt/share/.ssh
      - ./config.toml:/var/nextmini/config.toml
      - ./lenet5.py:/var/nextmini/lenet5.py
      - ./test.py:/var/nextmini/test.py
      - ./run_test.sh:/var/nextmini/run_test.sh
      - ./train.sh:/var/nextmini/train.sh
      - ./pyproject.toml:/var/nextmini/pyproject.toml
    depends_on:
      - controller
      - node3
    cap_add:
      - NET_ADMIN
    command: /bin/bash -c "mkdir -p /root/.ssh && cp -r /mnt/share/.ssh /root &&
      chmod 400 /root/.ssh/id_rsa &&
      sleep 11 &&
      /var/nextmini/nextmini ws://controller:3000"
