protocol = "tcp"
scheduler_type = "wrr"

[topology]
n_nodes = 6

[[link_rates]]
src_node_id = 1
dst_node_id = 2
rate = 100_496_714
bucket_size = 9000

[[link_rates]]
src_node_id = 2
dst_node_id = 3
rate = 99_861_735
bucket_size = 9000

[[link_rates]]
src_node_id = 3
dst_node_id = 4
rate = 100_647_688
bucket_size = 9000

[[link_rates]]
src_node_id = 4
dst_node_id = 5
rate = 101_523_029
bucket_size = 9000

[[link_rates]]
src_node_id = 5
dst_node_id = 6
rate = 99_765_846
bucket_size = 9000

[[link_rates]]
src_node_id = 6
dst_node_id = 1
rate = 99_765_863
bucket_size = 9000

[[link_rates]]
src_node_id = 2
dst_node_id = 1
rate = 101_579_212
bucket_size = 9000

[[link_rates]]
src_node_id = 3
dst_node_id = 2
rate = 100_767_434
bucket_size = 9000

[[link_rates]]
src_node_id = 4
dst_node_id = 3
rate = 99_530_525
bucket_size = 9000

[[link_rates]]
src_node_id = 5
dst_node_id = 4
rate = 100_542_560
bucket_size = 9000

[[link_rates]]
src_node_id = 6
dst_node_id = 5
rate = 99_536_582
bucket_size = 9000

[[link_rates]]
src_node_id = 1
dst_node_id = 6
rate = 99_534_270
bucket_size = 9000

[[routes]]
route = [1, 2]

[[routes]]
route = [2, 1]

[[routes]]
route = [2, 3]

[[routes]]
route = [3, 2]

[[routes]]
route = [3, 4]

[[routes]]
route = [4, 3]

[[routes]]
route = [4, 5]

[[routes]]
route = [5, 4]

[[routes]]
route = [5, 6]

[[routes]]
route = [6, 5]

[[routes]]
route = [6, 1]

[[routes]]
route = [1, 6]

