use core::panic;

use clap_serde_derive::ClapSerde;
use clap_serde_derive::clap;
use clap_serde_derive::clap::Parser;
use network_interface::{Addr, NetworkInterface, NetworkInterfaceConfig};
use serde::Deserialize;
use serde_json::Value;

use strato_messages::{ControllerToDataplane, MultiPathMethod, Protocol};

use crate::dataplane::scheduler::SchedulingDiscipline;

/// The choice of congestion control algorithm in QUIC. Only BBR and CUBIC are supported by s2n-quic.
#[derive(Clone, Default, Debug, PartialEq, Deserialize, clap::ValueEnum)]
#[serde(rename_all = "lowercase")]
pub enum CongestionControl {
    #[default]
    Bbr,
    Cubic,
}

#[derive(Parser)]
#[command(author, version, about)]
pub struct Args {
    /// The address of the server to connect to (e.g., 128.100.100.128).
    pub server_addr: String,

    /// The path to the configuration file.
    #[arg(short, long, default_value = "config.toml")]
    pub config_path: String,

    /// All other configuration options for the dataplane.
    #[clap(flatten)]
    pub args: <LocalConfigs as ClapSerde>::Opt,
}

/// Configuration options for the dataplane, read from a configuration file or from the command-line.
#[derive(ClapSerde, Debug, Clone, Deserialize)]
pub struct LocalConfigs {
    /// The server address
    #[default("".to_string())]
    #[arg(skip)]
    pub server_addr: String,

    /// The name of the private network this node might share with other nodes. This is used to identify
    /// nodes on the same network. Not specifying this field will cause the node to connect to other nodes
    /// via the public network addresses only.
    #[default("".to_string())]
    #[arg(long)]
    pub private_network_name: String,

    /// The name of the local network interface to use for communicating between nodes on the same subnet.
    #[default("eth0".to_string())]
    #[arg(long)]
    pub private_network_interface: String,

    /// The port to use for communicating between nodes on the same network.
    #[default("8080".to_string())]
    #[arg(long)]
    pub private_network_port: String,

    /// The name of the local network interface to use for communciating with nodes from a different subnet.
    #[default("eth0".to_string())]
    #[arg(long)]
    pub public_network_interface: String,

    /// The port to use for communicating with nodes from a different subnet.
    #[default("8080".to_string())]
    #[arg(long)]
    pub public_network_port: String,

    /// The node id to be used for this node. If not specified, a random id will be generated by the server.
    #[default("".to_string())]
    #[arg(long)]
    pub node_id: String,

    /// The interval at which metrics are collected and sent to the controller.
    #[default(1)]
    #[arg(long)]
    pub metrics_collection_interval: u64,

    /// The number of packet processors to use to process packets. Recommended to use a larger number on a machine
    /// with multiple cores for greater throughput. Use the number of CPU cores if set to 0.
    #[default(0)]
    #[arg(long)]
    pub num_packet_processors: usize,

    /// The address of the local network interface to use for communicating between nodes on the same subnet.
    #[default("".to_string())]
    #[arg(long)]
    pub private_network_addr: String,

    /// The address of the local network interface touse for communciating with nodes from a different subnet.
    #[default("".to_string())]
    #[arg(long)]
    pub public_network_addr: String,

    /// The name of the tun interface
    #[default("utun".to_string())]
    #[arg(long)]
    pub tun_interface_name: String,

    /// The MTU of the tun interface. A larger value reduces CPU load when trasmit large files, but increases
    /// cost of retransmission. The maximum value is 6400.
    #[default(1400)]
    #[arg(long)]
    pub mtu: i32,

    /// Set if the node should restart when the connection to the server is lost.
    #[default(false)]
    #[arg(long)]
    pub restart_on_disconnect: bool,

    /// Whether tokio-console logging should be enabled for performance fine-tuning.
    #[default(false)]
    #[arg(long)]
    pub enable_tokio_console: bool,

    /// Runtime fine-tuning: event_interval. A value of 0 uses Tokio's default seting. See
    /// https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.event_interval.
    #[default(0)]
    #[arg(long)]
    pub rt_event_interval: u32,

    /// Runtime fine-tuning: the number of worker threads. A value of 0 uses the same number as available
    /// CPU cores.
    #[default(0)]
    #[arg(long)]
    pub rt_n_worker_threads: usize,

    /// QUIC congestion control algorithm to use.
    #[default(CongestionControl::Bbr)]
    #[arg(long, value_enum)]
    pub quic_congestion_control: CongestionControl,
}

/// Creates a new instance of LocalConfigs.
pub fn new() -> LocalConfigs {
    let mut args = Args::parse();

    let mut cfgs = match std::fs::read_to_string(&args.config_path) {
        Ok(content) => match toml::from_str::<<LocalConfigs as ClapSerde>::Opt>(&content) {
            Ok(cfgs) => LocalConfigs::from(cfgs).merge(&mut args.args),
            Err(e) => {
                println!("Failed to parse config file (with error: {e}), using default values.");
                LocalConfigs::from(&mut args.args)
            }
        },
        Err(e) => {
            let fname = &args.config_path.clone();
            println!(
                "Failed to read the config file '{fname}' (with error: {e}), using default values."
            );
            LocalConfigs::from(&mut args.args)
        }
    };

    cfgs.server_addr = args.server_addr;

    // sets the private ipv4 address of the network interface for the private network
    // Defined by RFC 1918, private IP addresses fall within the following ranges:
    // 10.0.0.0 - 10.255.255.255 (10.0.0.0/8)
    // 172.16.0.0 - 172.31.255.255 (172.16.0.0/12)
    // 192.168.0.0 - 192.168.255.255 (192.168.0.0/16)
    if cfgs.private_network_addr.is_empty() {
        let itf_name = cfgs.private_network_interface.clone();

        // retrieves a list of all private network interfaces available on the system
        let network_interfaces = NetworkInterface::show().expect(
            "Failed to get the network interfaces. This is like due to the lack of privileges.",
        );

        let mut ipv4addr = String::new();

        // iterates over the list of network interfaces to find the one matching the specified name,
        // such as 'eth0'
        for itf in network_interfaces.iter() {
            if itf.name == itf_name {
                // for the matching interface, iterates over its associated addresses, looking for an
                // ipv4 address
                for addr in itf.addr.iter() {
                    if let Addr::V4(ipv4) = addr {
                        ipv4addr = ipv4.ip.to_string();
                    }
                }
            }
        }

        cfgs.private_network_addr = ipv4addr;
    }

    // sets the ipv4 address of the network interface for the public network
    if cfgs.public_network_addr.is_empty() {
        let itf_name = cfgs.public_network_interface.clone();

        // retrieves a list of all public network interfaces available on the system
        let network_interfaces = NetworkInterface::show().expect(
            "Failed to get the network interfaces. This is like due to the lack of privileges.",
        );

        let mut ipv4addr = String::new();

        // iterates over the list of network interfaces to find the one matching the specified name,
        // such as 'eth0'
        for itf in network_interfaces.iter() {
            if itf.name == itf_name {
                // for the matching interface, iterates over its associated addresses, looking for an
                // ipv4 address
                for addr in itf.addr.iter() {
                    if let Addr::V4(ipv4) = addr {
                        ipv4addr = ipv4.ip.to_string();
                    }
                }
            }
        }

        cfgs.public_network_addr = ipv4addr;
    }

    // sets the number of packet processors to the number of threads if it is 0
    if cfgs.num_packet_processors == 0 {
        cfgs.num_packet_processors = num_cpus::get();
    }

    println!("Using configs: {:#?}", cfgs);

    cfgs
}

/// Configuration options for the controller
#[derive(Clone)]
pub struct ControllerConfigs {
    /// The session ID
    pub session_id: [u8; 4],

    /// The node ID
    pub node_id: usize,

    /// The local network address
    pub strato_address: (u8, u8, u8, u8),

    /// The local network mask
    pub strato_mask: (u8, u8, u8, u8),

    /// The multi-path method
    pub multi_path_method: MultiPathMethod,

    /// The number of interfaces
    pub num_interfaces: usize,

    /// The transport protocol: TCP, UDP, or QUIC
    pub protocol: Protocol,

    /// The scheduling discipline
    pub scheduler_type: SchedulingDiscipline,
}

impl ControllerConfigs {
    pub fn new(data: Value) -> Self {
        let msg: ControllerToDataplane =
            serde_json::from_value(data).expect("Invalid controller message format");
        if let ControllerToDataplane::StartUp {
            node_id,
            addr,
            net_mask,
            session_id,
            num_interfaces,
            protocol,
            multi_path_method,
        } = msg
        {
            Self {
                session_id,
                node_id,
                strato_address: (addr[0], addr[1], addr[2], addr[3]),
                strato_mask: (net_mask[0], net_mask[1], net_mask[2], net_mask[3]),
                multi_path_method,
                num_interfaces,
                protocol,
                scheduler_type: SchedulingDiscipline::Fifo, // Default, could be made configurable
            }
        } else {
            panic!("Expected StartUp message from controller");
        }
    }
}
